Repository iiitl/Stuconnect, pull requests merged in 2025-03, with the labels that each got.

#12 Error Handling Enhanced
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/lib/utils.ts
Labels: accepted-14

#11 Fixed inconsistency in theme toggling
  Backend/public/temp/.gitkeep
  Frontend/src/components/modals/CreateChannelModal.tsx
  Frontend/src/components/navigation/ServerChannels.tsx
Labels: accepted-12

#27 removed dividing line when no mods present
  Frontend/src/components/navigation/ManageMembersItem.tsx
Labels: need-changes
